### ISSUE TITLE
How to download files from a remote http/ftp Sever from a libwebsokcet client

### ISSUE THREAD

**Issue by VenkyDevHub** [iamscottmoyers/simple-libwebsockets-example#1]
Hi Scott Moyers, @iamscottmoyers 

In the project I'm currently doing, I need to download the files from the a _**remote ftp/http**_ server using `libwebsocket` client. ([**My detailed question on Stack Overflow here**](https://stackoverflow.com/questions/45274233/libwebsockets-how-to-download-files-from-http-server-using-libwebsocket-client)).

Your example shows how to serve a file download request; But in my case, I need to download from a web server from client (written using _libwebsockets_).

Could you please help me with that? Which API I need to use in order to that? I have gone through all the [_API reference_](https://libwebsockets.org/lws-api-doc-v2.2-stable/html/modules.html) of _libwebsokcets_, but no luck finding the suitable API for the job. Please help. 

Thanks in Advance!

Regards,
@VenkyDevHub (Venky)

**Comment by iamscottmoyers** [comment]
Hi Venky,

I must admit I'm no expert in libwebsockets, I had a few weeks without a
job and was experimenting with an IoT project.

I'll take a look at the code again tonight and see if I can figure it out.

Good luck with your project! :)

Regards,
Scott.

**Comment by iamscottmoyers** [comment]
Hi Venky,

Sorry, I did this small project a few years ago and haven't looked at libwebsockets since. I barely understand the existing code let alone know how to extend it. I was trying to get some small regular data sent from a device to a client and be updated in real time which websockets seemed to be a good fit for. For file transfers I don't think you need the added complexity of websockets, I think you just need HTTP POST.

If you're working on ARM you might want to try and find out what the mbed micro-controllers do as their system is built to make things like DFU as easy as possible. They have a page on websockets here if that's what you need to use:
https://developer.mbed.org/cookbook/Websockets

Best of luck with the project,
Scott.

**Comment by VenkyDevHub** [comment]
Hi @iamscottmoyers Scott,

Thank you very much for your help. I'll dig little deep to find the solution. Thank you for your example code here, which has cleared lot of my confusions and made libwebsocket API little intuitive. Thanks a lot for your wishes. :)

Regards.
Venky.
